server:
  port: 8086

spring:
  application:
    name: AccountServiceApplication

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

#gateway:
#  url: http://localhost:8083


customer-service:
  url:  http://customer-service/
