server:
  port: 8085

spring:
  application:
    name: CardServiceApplication

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

account-service:
  url:  http://account-service/


